variable "cluster_ec2_instance_type" {}
variable "cluster_ec2_ami_id" {}
variable "subnet_id" {}
variable "key_pair" {}
variable "ec2_name" {}
variable "vpc_sg_id" {}
variable "ebs_device_name" {}
variable "ebs_delete_on_termination" {}
variable "ebs_volume_size_gb" {}