---
# tasks file for kubernetes_network
- name: Install Flannel network plugin
  ansible.builtin.shell: sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Taint master node to prevent workload scheduling
  ansible.builtin.shell: sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf taint nodes --all node-role.kubernetes.io/control-plane-