---
- name: Configure Kubernetes Master
  hosts: master
  become: yes
  roles:
    - kubernetes_master

- name: Configure Kubernetes Network
  hosts: master
  become: yes
  roles:
    - kubernetes_network

- name: Configure Kubernetes Worker
  hosts: worker
  become: yes
  roles:
    - kubernetes_worker