---
- name: Configure Kubernetes Master
  hosts: master
  become: yes
  roles:
    - master

- name: Configure Kubernetes Network
  hosts: master
  become: yes
  roles:
    - network

- name: Configure Kubernetes Worker
  hosts: worker
  become: yes
  roles:
    - worker